Developement.sh Install script completed

diff --git a/00_other_sources/shell_darealshinji/copy-dll-deps b/00_other_sources/shell_darealshinji/copy-dll-deps
--- a/00_other_sources/shell_darealshinji/copy-dll-deps
+++ b/00_other_sources/shell_darealshinji/copy-dll-deps
@@ -38,8 +38,8 @@ case "$(uname -o)" in
 esac
 
 function errorExit() {
-	echo ""
-	echo "error: $1"
+	echo -e ""
+	echo -e "error: $1"
 	exit 1
 }
 
@@ -55,12 +55,12 @@ function copy_dlls() {
 		export PATH="$dir:$PATH"
 		printf "analyzing \`$file'... "
 		depends -c -oc:"$txt" "$file"
-		echo "done"
+		echo -e "done"
 	fi
 
 	dlls="$(grep '^,.*\.DLL' "$txt" | cut -d '"' -f2 | tr [A-Z] [a-z])"
 	mkdir -p "$outdir"
-	echo "copy dependencies:"
+	echo -e "copy dependencies:"
 	for f in $dlls; do
 		# don't rely on depends.exe to print full paths
 		f="$(basename "$f")"
@@ -69,7 +69,7 @@ function copy_dlls() {
 			cp -vf "$dll" "$outdir"
 		else
 			dll="$(which $f)"
-			if ! $(echo "$dll" | grep -q '/c/Windows/'); then 
+			if ! $(echo -e "$dll" | grep -q '/c/Windows/'); then 
 				cp -vf "$dll" "$outdir"
 			fi
 		fi
@@ -92,7 +92,7 @@ function get_depends_exe() {
 		errorExit "\`wget' or \`curl' not in PATH"
 	fi
 
-	(echo "675ca981ddf557eb7d4550624157dbe5 *$zip" | \
+	(echo -e "675ca981ddf557eb7d4550624157dbe5 *$zip" | \
 	 md5sum -c - 2>/dev/null 1>/dev/null) || \
 		errorExit "incorrect checksum"
 
@@ -105,15 +105,15 @@ function get_depends_exe() {
 		errorExit "\`unzip' not in PATH"
 	fi
 
-	echo "done"
-	echo ""
+	echo -e "done"
+	echo -e ""
 }
 
 input="$1"
 outdir="$2"
 
 if [ -z "$input" ]; then
-	echo "usage: $0 <EXE|DLL|DIR> [<OUTDIR>]"
+	echo -e "usage: $0 <EXE|DLL|DIR> [<OUTDIR>]"
 	exit 1
 fi
 
@@ -140,7 +140,7 @@ if [ -d "$1" ]; then
 	fi
 	for f in "$1"/*.exe "$1"/*.dll ; do
 		copy_dlls "$f" "$outdir"
-		echo ""
+		echo -e ""
 	done
 elif [ -f "$1" ]; then
 	if [ "x$outdir" = "x" ]; then
diff --git a/00_other_sources/shell_darealshinji/grp2 b/00_other_sources/shell_darealshinji/grp2
--- a/00_other_sources/shell_darealshinji/grp2
+++ b/00_other_sources/shell_darealshinji/grp2
@@ -33,11 +33,11 @@
 #  filedata
 
 printHelp () {
-    echo "create an archive:"
-    echo "  $0 c archive.grp2 [file(s)|-]"
-    echo ""
-    echo "extract files from archive:"
-    echo "  $0 [x|e] archive.grp2"
+    echo -e "create an archive:"
+    echo -e "  $0 c archive.grp2 [file(s)|-]"
+    echo -e ""
+    echo -e "extract files from archive:"
+    echo -e "  $0 [x|e] archive.grp2"
 }
 
 id="\000<GROUP\000INDEX\000BEGIN>\000"
@@ -66,8 +66,8 @@ case $option in
     exit 0
     ;;
   *)
-    test -z $option || echo "error: unkown command \`$option'."
-    echo "See \`$0 --help' for available commands."
+    test -z $option || echo -e "error: unkown command \`$option'."
+    echo -e "See \`$0 --help' for available commands."
     exit 1
     ;;
 esac
@@ -75,7 +75,7 @@ esac
 if [ "$operation" = "create" ]; then
 
   if [ -e "$archive" ]; then
-    echo "error: \`$archive': file already exists"
+    echo -e "error: \`$archive': file already exists"
     exit 1
   fi
   if [ "$archive" != "-" ]; then
@@ -85,21 +85,21 @@ if [ "$operation" = "create" ]; then
   # start with \n so grep can find the index if
   # the archive was appended to another file
   eval printf \"\\n${id}\\n\" $out
-  eval echo $count $out
-  eval echo $checksum_format $out
+  eval echo -e $count $out
+  eval echo -e $checksum_format $out
 
   # filenames
   for n in `seq 1 $count`; do
-    eval echo "\$$n" $out
+    eval echo -e "\$$n" $out
   done
 
   # filesizes + checksums
   for n in `seq 1 $count`; do
     eval size=\$\(du -b "\$$n"\)
     eval checksum=\$\(\${checksum_format}sum -b "\$$n"\)
-    size=$(echo $size | awk '{print $1}')
-    checksum=$(echo $checksum | awk '{print $1}')
-    eval echo "$size $checksum" $out
+    size=$(echo -e $size | awk '{print $1}')
+    checksum=$(echo -e $checksum | awk '{print $1}')
+    eval echo -e "$size $checksum" $out
   done
 
   # append data
@@ -124,16 +124,16 @@ elif [ "$operation" = "extract" ]; then
     # calculate this first from old values
     skip_bytes=$(( $skip_bytes + $filesize ))
 
-    filesize=$(( $(echo "$filesize_checksum" | cut -d ' ' -f1) ))
-    checksum=$(echo "$filesize_checksum" | cut -d ' ' -f2)
+    filesize=$(( $(echo -e "$filesize_checksum" | cut -d ' ' -f1) ))
+    checksum=$(echo -e "$filesize_checksum" | cut -d ' ' -f2)
 
-    echo "extract \`$filename'"
+    echo -e "extract \`$filename'"
     mkdir -p "$(dirname "$filename")"
     tail -n+$data_begin "$archive" | dd count=$filesize skip=$skip_bytes bs=1 of="$filename"
 
     printf "verify checksum: "
-    echo "$checksum *$filename" | ${checksum_format}sum -c
-    echo
+    echo -e "$checksum *$filename" | ${checksum_format}sum -c
+    echo -e
   done
 
 fi
diff --git a/00_other_sources/shell_darealshinji/makeself-header b/00_other_sources/shell_darealshinji/makeself-header
--- a/00_other_sources/shell_darealshinji/makeself-header
+++ b/00_other_sources/shell_darealshinji/makeself-header
@@ -20,10 +20,10 @@ quiet="n"
 print_cmd_arg=""
 if type printf > /dev/null; then
     print_cmd="printf"
-elif test -x /usr/ucb/echo; then
-    print_cmd="/usr/ucb/echo"
+elif test -x /usr/ucb/echo -e; then
+    print_cmd="/usr/ucb/echo -e"
 else
-    print_cmd="echo"
+    print_cmd="echo -e"
 fi
 
 unset CDPATH
@@ -36,7 +36,7 @@ MS_Printf()
 MS_PrintLicense()
 {
   if test x"\$licensetxt" != x; then
-    echo \$licensetxt
+    echo -e \$licensetxt
     while true
     do
       MS_Printf "Please type y to accept, n otherwise: "
@@ -162,18 +162,18 @@ MS_Check()
     i=1
     for s in \$filesizes
     do
-		crc=\`echo \$CRCsum | cut -d" " -f\$i\`
+		crc=\`echo -e \$CRCsum | cut -d" " -f\$i\`
 		if test -x "\$MD5_PATH"; then
 			if test \`basename \$MD5_PATH\` = digest; then
 				MD5_ARG="-a md5"
 			fi
-			md5=\`echo \$MD5 | cut -d" " -f\$i\`
+			md5=\`echo -e \$MD5 | cut -d" " -f\$i\`
 			if test \$md5 = "00000000000000000000000000000000"; then
-				test x\$verb = xy && echo " \$1 does not contain an embedded MD5 checksum." >&2
+				test x\$verb = xy && echo -e " \$1 does not contain an embedded MD5 checksum." >&2
 			else
 				md5sum=\`MS_dd "\$1" \$offset \$s | eval "\$MD5_PATH \$MD5_ARG" | cut -b-32\`;
 				if test "\$md5sum" != "\$md5"; then
-					echo "Error in MD5 checksums: \$md5sum is different from \$md5" >&2
+					echo -e "Error in MD5 checksums: \$md5sum is different from \$md5" >&2
 					exit 2
 				else
 					test x\$verb = xy && MS_Printf " MD5 checksums are OK." >&2
@@ -182,13 +182,13 @@ MS_Check()
 			fi
 		fi
 		if test \$crc = "0000000000"; then
-			test x\$verb = xy && echo " \$1 does not contain a CRC checksum." >&2
+			test x\$verb = xy && echo -e " \$1 does not contain a CRC checksum." >&2
 		else
 			sum1=\`MS_dd "\$1" \$offset \$s | CMD_ENV=xpg4 cksum | awk '{print \$1}'\`
 			if test "\$sum1" = "\$crc"; then
 				test x\$verb = xy && MS_Printf " CRC checksums are OK." >&2
 			else
-				echo "Error in checksums: \$sum1 is different from \$crc" >&2
+				echo -e "Error in checksums: \$sum1 is different from \$crc" >&2
 				exit 2;
 			fi
 		fi
@@ -196,17 +196,17 @@ MS_Check()
 		offset=\`expr \$offset + \$s\`
     done
     if test "\$quiet" = "n";then
-    	echo " All good."
+    	echo -e " All good."
     fi
 }
 
 UnTAR()
 {
     if test "\$quiet" = "n"; then
-    	tar \$1vf - 2>&1 || { echo Extraction failed. > /dev/tty; kill -15 \$$; }
+    	tar \$1vf - 2>&1 || { echo -e Extraction failed. > /dev/tty; kill -15 \$$; }
     else
 
-    	tar \$1f - 2>&1 || { echo Extraction failed. > /dev/tty; kill -15 \$$; }
+    	tar \$1f - 2>&1 || { echo -e Extraction failed. > /dev/tty; kill -15 \$$; }
     fi
 }
 
@@ -233,39 +233,39 @@ do
 	shift
 	;;
     --info)
-	echo Identification: "\$label"
-	echo Target directory: "\$targetdir"
-	echo Uncompressed size: $USIZE KB
-	echo Compression: $COMPRESS
-	echo Date of packaging: $DATE
-	echo Built with Makeself version $MS_VERSION on $OSTYPE
-	echo Build command was: "$MS_COMMAND"
+	echo -e Identification: "\$label"
+	echo -e Target directory: "\$targetdir"
+	echo -e Uncompressed size: $USIZE KB
+	echo -e Compression: $COMPRESS
+	echo -e Date of packaging: $DATE
+	echo -e Built with Makeself version $MS_VERSION on $OSTYPE
+	echo -e Build command was: "$MS_COMMAND"
 	if test x\$script != x; then
-	    echo Script run after extraction:
-	    echo "    " \$script \$scriptargs
+	    echo -e Script run after extraction:
+	    echo -e "    " \$script \$scriptargs
 	fi
 	if test x"$copy" = xcopy; then
-		echo "Archive will copy itself to a temporary location"
+		echo -e "Archive will copy itself to a temporary location"
 	fi
 	if test x"$KEEP" = xy; then
-	    echo "directory \$targetdir is permanent"
+	    echo -e "directory \$targetdir is permanent"
 	else
-	    echo "\$targetdir will be removed after extraction"
+	    echo -e "\$targetdir will be removed after extraction"
 	fi
 	exit 0
 	;;
     --dumpconf)
-	echo LABEL=\"\$label\"
-	echo SCRIPT=\"\$script\"
-	echo SCRIPTARGS=\"\$scriptargs\"
-	echo archdirname=\"$archdirname\"
-	echo KEEP=$KEEP
-	echo COMPRESS=$COMPRESS
-	echo filesizes=\"\$filesizes\"
-	echo CRCsum=\"\$CRCsum\"
-	echo MD5sum=\"\$MD5\"
-	echo OLDUSIZE=$USIZE
-	echo OLDSKIP=`expr $SKIP + 1`
+	echo -e LABEL=\"\$label\"
+	echo -e SCRIPT=\"\$script\"
+	echo -e SCRIPTARGS=\"\$scriptargs\"
+	echo -e archdirname=\"$archdirname\"
+	echo -e KEEP=$KEEP
+	echo -e COMPRESS=$COMPRESS
+	echo -e filesizes=\"\$filesizes\"
+	echo -e CRCsum=\"\$CRCsum\"
+	echo -e MD5sum=\"\$MD5\"
+	echo -e OLDUSIZE=$USIZE
+	echo -e OLDSKIP=`expr $SKIP + 1`
 	exit 0
 	;;
     --lsm)
@@ -277,7 +277,7 @@ EOLSM
 	exit 0
 	;;
     --list)
-	echo Target directory: \$targetdir
+	echo -e Target directory: \$targetdir
 	offset=\`head -n $SKIP "\$0" | wc -c | tr -d " "\`
 	for s in \$filesizes
 	do
@@ -331,7 +331,7 @@ EOLSM
 	shift
 	;;
     --xwin)
-	finish="echo Press Return to close this window...; read junk"
+	finish="echo -e Press Return to close this window...; read junk"
 	xterm_loop=1
 	shift
 	;;
@@ -343,7 +343,7 @@ EOLSM
 	shift
 	break ;;
     -*)
-	echo Unrecognized flag : "\$1" >&2
+	echo -e Unrecognized flag : "\$1" >&2
 	MS_Help
 	exit 1
 	;;
@@ -353,7 +353,7 @@ EOLSM
 done
 
 if test "\$quiet" = "y" -a "\$verbose" = "y";then
-	echo Cannot be verbose and quiet at the same time. >&2
+	echo -e Cannot be verbose and quiet at the same time. >&2
 	exit 1
 fi
 
@@ -363,11 +363,11 @@ case "\$copy" in
 copy)
     tmpdir=\$TMPROOT/makeself.\$RANDOM.\`date +"%y%m%d%H%M%S"\`.\$\$
     mkdir "\$tmpdir" || {
-	echo "Could not create temporary directory \$tmpdir" >&2
+	echo -e "Could not create temporary directory \$tmpdir" >&2
 	exit 1
     }
     SCRIPT_COPY="\$tmpdir/makeself"
-    echo "Copying to a temporary location..." >&2
+    echo -e "Copying to a temporary location..." >&2
     cp "\$0" "\$SCRIPT_COPY"
     chmod +x "\$SCRIPT_COPY"
     cd "\$TMPROOT"
@@ -391,8 +391,8 @@ if test "\$nox11" = "n"; then
                         break
                     fi
                 done
-                chmod a+x \$0 || echo Please add execution rights on \$0
-                if test \`echo "\$0" | cut -c1\` = "/"; then # Spawn a terminal!
+                chmod a+x \$0 || echo -e Please add execution rights on \$0
+                if test \`echo -e "\$0" | cut -c1\` = "/"; then # Spawn a terminal!
                     exec \$XTERM -title "\$label" -e "\$0" --xwin "\$initargs"
                 else
                     exec \$XTERM -title "\$label" -e "./\$0" --xwin "\$initargs"
@@ -407,7 +407,7 @@ if test "\$targetdir" = "."; then
 else
     if test "\$keep" = y; then
 	if test "\$quiet" = "n";then
-	    echo "Creating directory \$targetdir" >&2
+	    echo -e "Creating directory \$targetdir" >&2
 	fi
 	tmpdir="\$targetdir"
 	dashp="-p"
@@ -416,8 +416,8 @@ else
 	dashp=""
     fi
     mkdir \$dashp \$tmpdir || {
-	echo 'Cannot create target directory' \$tmpdir >&2
-	echo 'You should try option --target dir' >&2
+	echo -e 'Cannot create target directory' \$tmpdir >&2
+	echo -e 'You should try option --target dir' >&2
 	eval \$finish
 	exit 1
     }
@@ -442,16 +442,16 @@ if test "\$quiet" = "n";then
 fi
 res=3
 if test "\$keep" = n; then
-    trap 'echo Signal caught, cleaning up >&2; cd \$TMPROOT; /bin/rm -rf \$tmpdir; eval \$finish; exit 15' 1 2 3 15
+    trap 'echo -e Signal caught, cleaning up >&2; cd \$TMPROOT; /bin/rm -rf \$tmpdir; eval \$finish; exit 15' 1 2 3 15
 fi
 
 leftspace=\`MS_diskspace \$tmpdir\`
 if test -n "\$leftspace"; then
     if test "\$leftspace" -lt $USIZE; then
-        echo
-        echo "Not enough space left in "\`dirname \$tmpdir\`" (\$leftspace KB) to decompress \$0 ($USIZE KB)" >&2
+        echo -e
+        echo -e "Not enough space left in "\`dirname \$tmpdir\`" (\$leftspace KB) to decompress \$0 ($USIZE KB)" >&2
         if test "\$keep" = n; then
-            echo "Consider setting TMPDIR to a directory with more free space."
+            echo -e "Consider setting TMPDIR to a directory with more free space."
         fi
         eval \$finish; exit 1
     fi
@@ -464,14 +464,14 @@ do
 			(PATH=/usr/xpg4/bin:\$PATH; cd "\$tmpdir"; chown -R \`id -u\` .;  chgrp -R \`id -g\` .)
 		fi
     else
-		echo >&2
-		echo "Unable to decompress \$0" >&2
+		echo -e >&2
+		echo -e "Unable to decompress \$0" >&2
 		eval \$finish; exit 1
     fi
     offset=\`expr \$offset + \$s\`
 done
 if test "\$quiet" = "n";then
-	echo
+	echo -e
 fi
 
 cd "\$tmpdir"
@@ -487,7 +487,7 @@ if test x"\$script" != x; then
 		eval \$script \$scriptargs \$*; res=\$?
     fi
     if test \$res -ne 0; then
-		test x"\$verbose" = xy && echo "The program '\$script' returned an error code (\$res)" >&2
+		test x"\$verbose" = xy && echo -e "The program '\$script' returned an error code (\$res)" >&2
     fi
 fi
 if test "\$keep" = n; then
diff --git a/00_other_sources/shell_darealshinji/makeself-header-pseudostatic b/00_other_sources/shell_darealshinji/makeself-header-pseudostatic
--- a/00_other_sources/shell_darealshinji/makeself-header-pseudostatic
+++ b/00_other_sources/shell_darealshinji/makeself-header-pseudostatic
@@ -16,10 +16,10 @@ filesizes="$filesizes"
 print_cmd_arg=""
 if type printf > /dev/null; then
 	print_cmd="printf"
-elif test -x /usr/ucb/echo; then
-	print_cmd="/usr/ucb/echo"
+elif test -x /usr/ucb/echo -e; then
+	print_cmd="/usr/ucb/echo -e"
 else
-	print_cmd="echo"
+	print_cmd="echo -e"
 fi
 
 MS_Printf()
@@ -66,18 +66,18 @@ MS_Check()
 	i=1
 	for s in \$filesizes
 	do
-		crc=\`echo \$CRCsum | cut -d" " -f\$i\`
+		crc=\`echo -e \$CRCsum | cut -d" " -f\$i\`
 		if test -x "\$MD5_PATH"; then
 			if test \`basename \$MD5_PATH\` = digest; then
 				MD5_ARG="-a md5"
 			fi
-			md5=\`echo \$MD5 | cut -d" " -f\$i\`
+			md5=\`echo -e \$MD5 | cut -d" " -f\$i\`
 			if test \$md5 = "00000000000000000000000000000000"; then
-				test x\$verb = xy && echo " \$1 does not contain an embedded MD5 checksum." >&2
+				test x\$verb = xy && echo -e " \$1 does not contain an embedded MD5 checksum." >&2
 			else
 				md5sum=\`MS_dd "\$1" \$offset \$s | eval "\$MD5_PATH \$MD5_ARG" | cut -b-32\`;
 				if test "\$md5sum" != "\$md5"; then
-					echo "Error in MD5 checksums: \$md5sum is different from \$md5" >&2
+					echo -e "Error in MD5 checksums: \$md5sum is different from \$md5" >&2
 					exit 2
 				else
 					test x\$verb = xy && MS_Printf " MD5 checksums are OK." >&2
@@ -86,13 +86,13 @@ MS_Check()
 			fi
 		fi
 		if test \$crc = "0000000000"; then
-			test x\$verb = xy && echo " \$1 does not contain a CRC checksum." >&2
+			test x\$verb = xy && echo -e " \$1 does not contain a CRC checksum." >&2
 		else
 			sum1=\`MS_dd "\$1" \$offset \$s | CMD_ENV=xpg4 cksum | awk '{print \$1}'\`
 			if test "\$sum1" = "\$crc"; then
 				test x\$verb = xy && MS_Printf " CRC checksums are OK." >&2
 			else
-				echo "Error in checksums: \$sum1 is different from \$crc" >&2
+				echo -e "Error in checksums: \$sum1 is different from \$crc" >&2
 				exit 2;
 			fi
 		fi
@@ -103,13 +103,13 @@ MS_Check()
 
 UnTAR()
 {
-	tar \$1f - 2>&1 || { echo Extraction failed. > /dev/tty; kill -15 \$$; }
+	tar \$1f - 2>&1 || { echo -e Extraction failed. > /dev/tty; kill -15 \$$; }
 }
 
 tmpdir="\$TMPROOT/selfgz\$\$\$RANDOM"
 mkdir -p \$tmpdir || {
-	echo 'Cannot create target directory' \$tmpdir >&2
-	echo 'You should try option --target dir' >&2
+	echo -e 'Cannot create target directory' \$tmpdir >&2
+	echo -e 'You should try option --target dir' >&2
 	eval true
 	exit 1
 }
@@ -119,14 +119,14 @@ if test x\$SETUP_NOCHECK != x1; then
 fi
 offset=\`head -n $SKIP "\$0" | wc -c | tr -d " "\`
 
-trap 'echo Signal caught, cleaning up >&2; cd \$TMPROOT; rm -rf \$tmpdir; eval true; exit 15' 1 2 3 15
+trap 'echo -e Signal caught, cleaning up >&2; cd \$TMPROOT; rm -rf \$tmpdir; eval true; exit 15' 1 2 3 15
 
 leftspace=\`MS_diskspace \$tmpdir\`
 if test -n "\$leftspace"; then
 	if test "\$leftspace" -lt $USIZE; then
-		echo
-		echo "Not enough space left in "\`dirname \$tmpdir\`" (\$leftspace KB) to decompress \$0 ($USIZE KB)" >&2
-		echo "Consider setting TMPDIR to a directory with more free space."
+		echo -e
+		echo -e "Not enough space left in "\`dirname \$tmpdir\`" (\$leftspace KB) to decompress \$0 ($USIZE KB)" >&2
+		echo -e "Consider setting TMPDIR to a directory with more free space."
 		eval true; exit 1
 	fi
 fi
@@ -136,8 +136,8 @@ do
 	if MS_dd_Progress "\$0" \$offset \$s | eval "$GUNZIP_CMD" | ( cd "\$tmpdir"; UnTAR x ) 1>/dev/null; then
 		(PATH=/usr/xpg4/bin:\$PATH; cd "\$tmpdir"; chown -R \`id -u\` .;  chgrp -R \`id -g\` .)
 	else
-		echo >&2
-		echo "Unable to decompress \$0" >&2
+		echo -e >&2
+		echo -e "Unable to decompress \$0" >&2
 		eval true; exit 1
 	fi
 	offset=\`expr \$offset + \$s\`
diff --git a/00_other_sources/shell_darealshinji/xzexe b/00_other_sources/shell_darealshinji/xzexe
--- a/00_other_sources/shell_darealshinji/xzexe
+++ b/00_other_sources/shell_darealshinji/xzexe
@@ -63,15 +63,15 @@ res=0
 while :; do
   case $1 in
   -d) decomp=1; shift;;
-  --h*) exec echo "$usage";;
-  --v*) exec echo "$version";;
+  --h*) exec echo -e "$usage";;
+  --v*) exec echo -e "$version";;
   --) shift; break;;
   *) break;;
   esac
 done
 
 if test $# -eq 0; then
-  echo >&2 "$0: missing operand
+  echo -e >&2 "$0: missing operand
 Try \`$0 --help' for more information."
   exit 1
 fi
@@ -91,29 +91,29 @@ for i do
   esac
   if test ! -f "$file" || test ! -r "$file"; then
     res=$?
-    echo >&2 "$0: $i is not a readable regular file"
+    echo -e >&2 "$0: $i is not a readable regular file"
     continue
   fi
   if test $decomp -eq 0; then
     if sed -e 1d -e 2q "$file" | grep "^skip=[0-9][0-9]*$" >/dev/null; then
-      echo >&2 "$0: $i is already xzexe'd"
+      echo -e >&2 "$0: $i is already xzexe'd"
       continue
     fi
   fi
   if test -u "$file"; then
-    echo >&2 "$0: $i has setuid permission, unchanged"
+    echo -e >&2 "$0: $i has setuid permission, unchanged"
     continue
   fi
   if test -g "$file"; then
-    echo >&2 "$0: $i has setgid permission, unchanged"
+    echo -e >&2 "$0: $i has setgid permission, unchanged"
     continue
   fi
   case /$file in
   */basename | */bash | */cat | */chmod | */cp | \
-  */dirname | */echo | */expr | \
+  */dirname | */echo -e | */expr | \
   */ln | */mkdir | */mktemp | */mv | */rm | \
   */sed | */sh | */sleep | */test | */tail | */xz)
-    echo >&2 "$0: $i might depend on itself"; continue;;
+    echo -e >&2 "$0: $i might depend on itself"; continue;;
   esac
 
   dir=`dirname "$file"` || dir=$TMPDIR
@@ -129,7 +129,7 @@ for i do
     tmp=$dir/xzexe$$
   fi && { cp -p "$file" "$tmp" 2>/dev/null || cp "$file" "$tmp"; } || {
     res=$?
-    echo >&2 "$0: cannot copy $file"
+    echo -e >&2 "$0: cannot copy $file"
     continue
   }
   if test -w "$tmp"; then
@@ -138,7 +138,7 @@ for i do
     writable=0
     chmod u+w "$tmp" || {
       res=$?
-      echo >&2 "$0: cannot chmod $tmp"
+      echo -e >&2 "$0: cannot chmod $tmp"
       continue
     }
   fi
@@ -167,7 +167,7 @@ xztmp=$xztmpdir/$0
 case $0 in
 -* | */*'
 ')mkdir -p "$xztmp" && rm -r "$xztmp";;*/*)xztmp=$xztmpdir/`basename "$0"`;;esac||{(exit 127);exit 127;}
-case `echo X | tail -n +1 2>/dev/null` in
+case `echo -e X | tail -n +1 2>/dev/null` in
 X)tail_n=-n;;*)tail_n=;;esac
 if tail $tail_n +$skip <"$0" | xz -cd > "$xztmp";then
 umask $umask
@@ -176,14 +176,14 @@ chmod 700 "$xztmp"
 "$xztmp" ${1+"$@"}
 res=$?
 else
-echo>&2 "Cannot decompress $0"
+echo -e>&2 "Cannot decompress $0"
 (exit 127); res=127
 fi
 exit $res
 EOF
     xz -cv9 "$file") > "$tmp" || {
       res=$?
-      echo >&2 "$0: compression not possible for $i, file unchanged."
+      echo -e >&2 "$0: compression not possible for $i, file unchanged."
       continue
     }
 
@@ -195,29 +195,29 @@ EOF
     skip=[0-9] | skip=[0-9][0-9] | skip=[0-9][0-9][0-9])
       eval "$skip_line";;
     esac
-    case `echo X | tail -n +1 2>/dev/null` in
+    case `echo -e X | tail -n +1 2>/dev/null` in
     X) tail_n=-n;;
     *) tail_n=;;
     esac
     tail $tail_n +$skip "$file" | xz -cd > "$tmp" || {
       res=$?
-      echo >&2 "$0: $i probably not in xzexe format, file unchanged."
+      echo -e >&2 "$0: $i probably not in xzexe format, file unchanged."
       continue
     }
   fi
   test $writable -eq 1 || chmod u-w "$tmp" || {
     res=$?
-    echo >&2 "$0: $tmp: cannot chmod"
+    echo -e >&2 "$0: $tmp: cannot chmod"
     continue
   }
   ln -f "$file" "$file~" || {
     res=$?
-    echo >&2 "$0: cannot backup $i as $i~"
+    echo -e >&2 "$0: cannot backup $i as $i~"
     continue
   }
   mv -f "$tmp" "$file" || {
     res=$?
-    echo >&2 "$0: cannot rename $tmp to $i"
+    echo -e >&2 "$0: cannot rename $tmp to $i"
     continue
   }
   tmp=
